# deployment for the nodejs website, uses nginx image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-website
  template:
    metadata:
      labels:
        app: my-node-website
    spec:
      containers:
        - name: my-node-website
          image: localhost:5000/my-node-website:latest 
          imagePullPolicy: Always 
          ports:
            - containerPort: 80
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: host
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: database
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: PGPORT
               value: "5432" # Default PostgreSQL port
