# deployment for the nodejs website, uses nginx image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-website
  template:
    metadata:
      labels:
        app: my-node-website
    spec:
      containers:
        - name: my-node-website
          image: us-west1-docker.pkg.dev/idme-demo-429818/my-node-website:init
          ports:
            - containerPort: 80
