name: GCP Kubernetes Deployment

on:
    workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: self-hosted
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: 'terraform/website'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Terraform Init
        run: terraform init
        # env:
        #   GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Format
        run: terraform fmt -check
        # env:
        #   GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        # env:
        #   GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Plan
        run: terraform plan -out tfplan
        # env:
        #   GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Apply
        run: terraform apply tfplan
        # env:
        #   GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
