name: Vault Secret Retrieval Test

on:
    workflow_dispatch:



permissions:
  contents: read
  id-token: write

jobs:
  test-vault-access:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: 'terraform/vault-test'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v2
        id: get_vault_secret
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          role: github-actions-role  # Replace with your Vault role name
          # Assuming you have a secret named "username" under path "secret/data/github-actions/credentials" in Vault
          secrets: kv-test/data/test test | SHOW

      - name: Display Secret Value
        run: |
          echo "Retrieved secret: ${{ secrets.SHOW }}"
          # Additional test logic: verify if the retrieved value matches expected value
          name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
  
      - name: Terraform Init
        run: terraform init

      - name: Output Secret in Terraform
        run: |
            echo "username=${{ steps.get_vault_secret.outputs.username }}" >> terraform.tfvars
            terraform apply -auto-approve

      - name: Show Outputs (Optional)
        run: terraform output 

      - name: Cleanup (Optional)
        run: terraform destroy -auto-approve

      # Optional: Run additional tests/scripts that use the retrieved secret
